const dogData = [
   {
      id: 1,
      name: "Clifton",
      breed: "Croatian Sheepdog",
      gender: "male",
      price: 150,
      url: "https://cdn2.thedogapi.com/images/BykZ7ecVX_1280.jpg",
   },
   {
      id: 2,
      name: "Danyka",
      breed: "Pharaoh Hound",
      gender: "female",
      price: 399,
      url: "https://cdn2.thedogapi.com/images/SkJfGecE7_1280.jpg",
   },
   {
      id: 3,
      name: "Neha",
      breed: "Shikoku",
      gender: "male",
      price: 80,
      url: "https://cdn2.thedogapi.com/images/HkAVQl9VX_1280.jpg",
   },
   {
      id: 4,
      name: "Aracely",
      breed: "Border Collie",
      gender: "female",
      price: 750,
      url: "https://cdn2.thedogapi.com/images/HkqBYu3SX_1280.jpg",
   },
   {
      id: 5,
      name: "Gilberto",
      breed: "Kangol",
      gender: "male",
      price: 439,
      url: "https://cdn2.thedogapi.com/images/WVawT4Gap.jpg",
   },
   {
      id: 6,
      name: "Thalia",
      breed: "Siberian Husky",
      gender: "female",
      price: 599,
      url: "https://cdn2.thedogapi.com/images/GhtSdrW29.jpg",
   },
   {
      id: 7,
      name: "Lula",
      breed: "Beagle",
      gender: "female",
      price: 150,
      url: "https://cdn2.thedogapi.com/images/ikfu-FNqJ.jpg",
   },
   {
      id: 8,
      name: "Monique",
      breed: "Shitzu",
      gender: "female",
      price: 80,
      url: "https://cdn2.thedogapi.com/images/mhikcBw9U.jpg",
   },
   {
      id: 9,
      name: "Monty",
      breed: "Shiba Inu",
      gender: "male",
      price: 450,
      url: "https://cdn2.thedogapi.com/images/oG7h1MuxP.jpg",
   },
   {
      id: 10,
      name: "Dave",
      breed: "Jonangi",
      gender: "male",
      price: 199,
      url: "https://cdn2.thedogapi.com/images/SwxIgmxlN.jpg",
   },
   {
      id: 11,
      name: "Rosella",
      breed: "Staffy",
      gender: "female",
      price: 99,
      url: "https://cdn2.thedogapi.com/images/4Fw1A7oD8.jpg",
   },
   {
      id: 12,
      name: "Rosalind",
      breed: "Miniature Daschund",
      gender: "female",
      price: 649,
      url: "https://cdn2.thedogapi.com/images/9I-nz55bf.png",
   },
   {
      id: 13,
      name: "Regan",
      breed: "Husky",
      gender: "male",
      price: 150,
      url: "https://cdn2.thedogapi.com/images/C4iKU-xir.jpg",
   },
   {
      id: 14,
      name: "Jazelyn",
      breed: "Pitbull",
      gender: "female",
      price: 359,
      url: "https://cdn2.thedogapi.com/images/DSgAKoZve.jpg",
   },
   {
      id: 15,
      name: "Minerva",
      breed: "Molossus of Epirus",
      gender: "male",
      price: 259,
      url: "https://cdn2.thedogapi.com/images/B1pDZx9Nm_1280.jpg",
   },
   {
      id: 16,
      name: "Thalia",
      breed: "Siberian Husky",
      gender: "female",
      price: 150,
      url: "https://cdn2.thedogapi.com/images/GhtSdrW29.jpg",
   },
   {
      id: 17,
      name: "Paul",
      breed: "Labrador",
      gender: "male",
      price: 999,
      url: "https://cdn2.thedogapi.com/images/5Qdip6GTm.jpg",
   },
   {
      id: 18,
      name: "Sabryna",
      breed: "German Shepherd",
      gender: "female",
      price: 659,
      url: "https://cdn2.thedogapi.com/images/edNIMgpSw.jpg",
   },
   {
      id: 19,
      name: "Tremaine",
      breed: "Newfoundland",
      gender: "male",
      price: 59,
      url: "https://cdn2.thedogapi.com/images/Q6H9UcRZB.jpg",
   },
   {
      id: 20,
      name: "Santino",
      breed: "Borzol",
      gender: "male",
      price: 159,
      url: "https://cdn2.thedogapi.com/images/wXi4G5qEG.png",
   },
];

export default dogData;
